<a href="https://colab.research.google.com/github/teestar5/lesson00/blob/NeJron/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B_%D0%B2_Python_%D0%B8_%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B_NumPy%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# список
a = [1,2,3]
type(a)

list

In [ ]:
# массив numpy
a = np.array([1,2,3])
type(a)

numpy.ndarray

### Создание массивов

np.array() - создание массива из объекта списка или любого другого массива

In [ ]:
# список
a = [10,20,30,40]

# массив из списка
np.array(a)

array([10, 20, 30, 40])

In [ ]:
# массив (одномерный) из списка
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
# массив (двумерный) из списка списков
np.array([[1,2,3],
          [4,5,6]], dtype=float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
# создадим массив из значений разного типа
np.array([1,2,3,'a','b',0.55])

array(['1', '2', '3', 'a', 'b', '0.55'], dtype='<U32')

Как мы видим, все значения автоматически переведены в строковый формат, так как все значения массива numpy должны быть однотипными.

np.zeros() - создание массива нулей, заданной размерности

In [ ]:
# массив (одномерный) нулей
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
# массив (двумерный) нулей
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

np.ones() - создание массива елиниц, заданной размерности

In [ ]:
# массив (одномерный) единиц
np.ones(3)

array([1., 1., 1.])

In [ ]:
# массив (двумерный) единиц
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

np.eye() - создание массива нулей с единицами на главной диагонали

In [ ]:
# по умолчанию массив всегда квадратный
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# не квадратный массив
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

np.full() - создание массива с указанными значениями

In [ ]:
# заполним массив значениями 42
np.full((4,2), 42)

array([[42, 42],
       [42, 42],
       [42, 42],
       [42, 42]])

In [ ]:
# заполним массив значениями 3, 4
np.full((4,2), (3,4))

array([[3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

При заполнении массива несколькими значениями количество значений должно совпадать с количеством столбцов массива

In [ ]:
# заполним массив значениями "кислый"
np.full((4,2), "кислый")

array([['кислый', 'кислый'],
       ['кислый', 'кислый'],
       ['кислый', 'кислый'],
       ['кислый', 'кислый']], dtype='<U6')

np.arange(start, stop, step) - создание массива из последовательности равномерно распределенных чисел

In [ ]:
# массив значений от 0 до 10
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# массив значений от 5 до 10
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
# массив четных значений от 0 до 10
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

np.linspace(start, stop, num, endpoint) - создание массива из последовательности равномерно распределенных чисел с указанием количества точек

In [ ]:
# массив 5 чисел с плавающей точкой от 0.1 до 0.5 включительно
np.linspace(0.1, 0.5, 5)

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [ ]:
# массив 5 чисел с плавающей точкой от 0.1 до 0.5
np.linspace(0.1, 0.5, 5, endpoint=False)

array([0.1 , 0.18, 0.26, 0.34, 0.42])

### Определение / изменение размерности

Определение размерности массива

In [ ]:
# массив (одномерный) a
a = np.arange(12)
print(a)
print()

# массив (двумерный) b
b = np.array([[1,2,3],[4,5,6]])
print(b)
print()

# размерность массива a
print(a.shape)

# размерность массива b
print(b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[1 2 3]
 [4 5 6]]

(12,)
(2, 3)


Изменение размерности

In [ ]:
# приведение многомерного массива к одномерному
b.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# приведение многомерного массива к одномерному (2 способ)
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# приведение многомерного массива к одномерному (2 способ) с попеременным порядком
b.ravel(order='F')

array([1, 4, 2, 5, 3, 6])

In [ ]:
# изменение формы массива с (12) на (3,4)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# изменение формы массива с (12) на (6,2)
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
# изменение формы массива с (12) на (12,1)
a.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

При использовании метода `reshape()` важно помнить, что форма массива прямоугольная и количество элементов не меняется, следовательно значения новой размерности должны соответствовать этому условию.

Транспонирование

In [ ]:
# размерность массива b
print(b.shape)

b

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# транспонирование массива b
c = b.transpose()

# размерность массива с
print(c.shape)

c

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# транспонирование одномерного массива (вектора)
# метод .T так же выполняет транспонирование
np.array([1,2,3,4]).T

array([1, 2, 3, 4])

При транспонировании одномерного массива, с ним ничего не происходит.

Если мы хотим из строки сделать колонку, то нужно добавить одну ось.

In [ ]:
# транспонирование двумерного массива
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

Смещение указанной оси

In [ ]:
# создадим трёхмерный массив
a = np.ones((2,3,5))
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
# сдвинем ось 2 на место 0
np.rollaxis(a, 2, 0)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
# проверим получившуюся размерность
np.rollaxis(a, 2, 0).shape

(5, 2, 3)

Замена выбранных двух осей местами

In [ ]:
# поменяем местами оси 0 и 2
np.swapaxes(a, 2, 0)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
# поверим размерность
np.swapaxes(a, 2, 0).shape

(5, 3, 2)

Отличие функций `rollaxis` и `swapaxes` в том, что в первом случае, когда мы передвигаем выбраннуую ось, остальные сдвигаются, а во втором случае мы просто меняем 2 выбранные оси местами (при этом остальные оси остаются без изменения).

Удаление осей с размерностью 1

In [ ]:
# создадим массив (трехмерный)
a = np.array([[[1]],[[2]]])
a

array([[[1]],

       [[2]]])

In [ ]:
# проверим размерность
a.shape

(2, 1, 1)

In [ ]:
# удалим все оси, размерность которых 1
b = a.squeeze()
b

array([1, 2])

In [ ]:
# проверим размерность
b.shape

(2,)

In [ ]:
# удалим ось 1 с размерностью 1
a.squeeze(1)

array([[1],
       [2]])

Добавление оси с размерностью 1

In [ ]:
# создадим массив нулей
a = np.zeros((3,2))
print(a)
a.shape

[[0. 0.]
 [0. 0.]
 [0. 0.]]


(3, 2)

In [ ]:
# добавим ось
print(np.expand_dims(a, 0))

# проверим размерность
np.expand_dims(a, 0).shape

[[[0. 0.]
  [0. 0.]
  [0. 0.]]]


(1, 3, 2)

In [ ]:
# добавим ось в другое место
print(np.expand_dims(a, 2))

# проверим размерность
np.expand_dims(a, 2).shape

[[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]]


(3, 2, 1)

### Массивы случайных значений

np.random.rand(shape) - cоздание массива случайных значений с плавающей точкой от 0 до 1

In [ ]:
# случайное значение
np.random.rand()

0.48213751146398154

In [ ]:
# массив (одномерный) случайных значений
np.random.rand(4)

array([0.1912649 , 0.98563695, 0.2284574 , 0.21993   ])

In [ ]:
# массив (двумерный) случайных значений
np.random.rand(3,2)

array([[0.09054214, 0.47824919],
       [0.87380312, 0.19682686],
       [0.09854667, 0.65995418]])

np.random.randint(start,stop,shape) - создание массива случайных целочисленных значений из выбранного диапазона

In [ ]:
# массив (одномерный) случайных целочисленных значений от 0 до 10
np.random.randint(0,10,3)

array([6, 7, 5])

In [ ]:
# массив (двумерный) случайных целочисленных значений от 5 до 15
np.random.randint(5,15,(2,2))

array([[ 5, 13],
       [ 7,  9]])

np.random.uniform(start,stop,shape) - создание массива случайных значений с плавающей точкой из выбранного диапазона

In [ ]:
# массив 5 случайных значений float от 10 до 20
np.random.uniform(10,20,5)

array([11.0378546 , 15.51237958, 18.39808912, 14.55936902, 14.98707978])

In [ ]:
# массив случайных значений float от 9 до 10
np.random.uniform(9,10,(5,1))

array([[9.41811778],
       [9.82930997],
       [9.3866402 ],
       [9.04455905],
       [9.33692312]])

np.random.choice(array,size) - функция случайного выбора значений из списка/массива

In [ ]:
# список значений
a = [1,2,3,4,5]

# выбираем одно случайное значение из списка
np.random.choice(a)

4

In [ ]:
# список значений
a = ["a",2,3,"b",5]

# выбираем одно случайное значение из списка
np.random.choice(a)

'a'

In [ ]:
# список значений
a = ["gray","yellow","black","pink","white","cyan"]

# выбираем 2 случайных значения из списка
np.random.choice(a, 2)

array(['gray', 'pink'], dtype='<U6')

### Математические операции

Массив и скалярная величина

In [ ]:
# массив единиц
a = np.ones((3,2))

print('Сложение:\n', a + 5)
print()

print('Вычитание:\n', a - 1)
print()

print('Умножение:\n', a * 5)
print()

print('Деление:\n', a / 3)
print()


Сложение:
 [[6. 6.]
 [6. 6.]
 [6. 6.]]

Вычитание:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

Умножение:
 [[5. 5.]
 [5. 5.]
 [5. 5.]]

Деление:
 [[0.33333333 0.33333333]
 [0.33333333 0.33333333]
 [0.33333333 0.33333333]]



Два массива одинаковой размерности

In [ ]:
# массив a
a = np.array([[1,2,3],[4,5,6]])

# массив b
b = np.array([[1,1,1],[10,20,30]])

print('Сложение:\n', a + b)
print()

print('Вычитание:\n', b - a)
print()

print('Умножение:\n', a * b)
print()

print('Деление:\n', b / a)

Сложение:
 [[ 2  3  4]
 [14 25 36]]

Вычитание:
 [[ 0 -1 -2]
 [ 6 15 24]]

Умножение:
 [[  1   2   3]
 [ 40 100 180]]

Деление:
 [[1.         0.5        0.33333333]
 [2.5        4.         5.        ]]


Матричное умножение

Для выполнения матричного умножения должны совпадать последняя ось первого массива и первая ось последнего массива.

In [ ]:
# размерность массива a
a.shape

(2, 3)

In [ ]:
# размерность транспонированного массива b
b.T.shape

(3, 2)

In [ ]:
print('Матричное умножение:\n', a @ b.T)

Матричное умножение:
 [[  6 140]
 [ 15 320]]


Для матричного умножения вместо знака @ можно использовать функцию `np.dot()`.

In [ ]:
print('Матричное умножение:\n', np.dot(a,b.T))

Матричное умножение:
 [[  6 140]
 [ 15 320]]


### Индексация и срезы

In [ ]:
# массив a
a = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
# выбор конкретного элемента массива (индексация)
print(a[0,0])
print(a[0,2])
print(a[1,1])

1
3
5


In [ ]:
# срезы элементов
print(a[0:2,0])
print(a[0,:])
print(a[1:,:1])
print(a[1,...])

[1 4]
[1 2 3]
[[4]]
[4 5 6]


Логическая индексация

In [ ]:
# выберем те элементы массива, которые больше 4
a[a>4]

array([5, 6])

In [ ]:
# выберем те элементы массива, которые не равны 1 и 2
a[(a!=1)&(a!=2)]

array([3, 4, 5, 6])

### Поиск и сортировка в numpy

Сортировка одномерных массивов numpy

In [ ]:
# массив (одномерный) a
a = np.random.randint(1,100,20)
a

array([75, 74, 70, 56, 92, 35, 74, 62, 11, 15, 70, 24, 60, 95, 50, 10, 52,
       63, 24, 64])

In [ ]:
# отсортируем массив a
np.sort(a)

array([10, 11, 15, 24, 24, 35, 50, 52, 56, 60, 62, 63, 64, 70, 70, 74, 74,
       75, 92, 95])

In [ ]:
# отсортируем массив a при помощи другого алгоритма, например ‘mergesort’
np.sort(a, kind='mergesort')

array([10, 11, 15, 24, 24, 35, 50, 52, 56, 60, 62, 63, 64, 70, 70, 74, 74,
       75, 92, 95])

In [ ]:
# отсортируем массив a и получим его индексы, вместо значений
np.argsort(a)

array([15,  8,  9, 18, 11,  5, 14, 16,  3, 12,  7, 17, 19,  2, 10,  6,  1,
        0,  4, 13])

In [ ]:
# если мы хотим инвертировать сортированный массив, то можно выполнить срез
np.sort(a)[::-1]

array([95, 92, 75, 74, 74, 70, 70, 64, 63, 62, 60, 56, 52, 50, 35, 24, 24,
       15, 11, 10])

Сортировка двумерных массивов numpy

In [ ]:
# массив (двумерный) b
b = np.random.randint(1,100,(3,4))
b

array([[29, 17, 51,  6],
       [34, 34, 74, 40],
       [61,  7, 74, 39]])

In [ ]:
# отсортируем массив b по оси 0
np.sort(b, axis=0)

array([[29,  7, 51,  6],
       [34, 17, 74, 39],
       [61, 34, 74, 40]])

In [ ]:
# отсортируем массив b по оси 1
np.sort(b, axis=1)

array([[ 6, 17, 29, 51],
       [34, 34, 40, 74],
       [ 7, 39, 61, 74]])

In [ ]:
# отсортируем массив b по оси 0 и получим его индексы, вместо значений
np.argsort(b, axis=0)

array([[0, 2, 0, 0],
       [1, 0, 1, 2],
       [2, 1, 2, 1]])

Поиск элементов в массивах numpy

In [ ]:
# массив (одномерный) a
a = np.random.randint(1,100,10)
a

array([76, 24, 18, 70, 63, 91, 47, 32, 16, 29])

In [ ]:
# найдем максимальный и минимальный элементы массива a
print(a.max())
print(a.min())

91
16


In [ ]:
# найдем индексы максимального и минимального элементов массива a
print(a.argmax())
print(a.argmin())

5
8


In [ ]:
# найдем сумму всех элементов
a.sum()

466

In [ ]:
# найдем среднее элементов массива a
a.mean()

46.6

In [ ]:
# найдем индексы элементов, значения которых больше 50
np.where(a>50)

(array([0, 3, 4, 5]),)

np.where(condition,x,y) - возвращает элементы, выбранные из x или y в зависимости от условия

In [ ]:
# значения меньше 70 заменим на 333, а значения больше или равные 70 заменим на 888
np.where(a<70,333,888)

array([888, 333, 333, 888, 333, 888, 333, 333, 333, 333])

In [ ]:
# значения больше 40 заменим на 0, а значения равные или меньше 40 оставим без именения
np.where(a>40,0,a)

array([ 0, 24, 18,  0,  0,  0,  0, 32, 16, 29])

### Сравнение скорости обработки массивов numpy со списками

Сравним скорость работы изменения массива по условию со скоростью изменения списка по условию

In [ ]:
# создаем массив случайных значений размера 2000 на 3000
a = np.random.randint(1,100,(2000,3000))
a

array([[51,  3, 83, ...,  7, 61, 46],
       [ 9,  8, 20, ..., 35, 21, 75],
       [98, 70,  9, ..., 36, 37, 49],
       ...,
       [10, 67, 19, ..., 89, 59,  2],
       [54, 98,  1, ..., 91, 32, 42],
       [58, 99, 46, ..., 94,  9, 21]])

In [ ]:
# переводим массив в список
list_a = a.tolist()

In [ ]:
# поверим размерность списка списков
print(len(list_a))
print(len(list_a[0]))

2000
3000


In [ ]:
%%timeit
# запустим выполнение условия:
# значения больше 40 заменим на 0, а значения равные или меньше 40 оставим без именения
for i in range(len(list_a)):
  for j in range(len(list_a[i])):
    if list_a[i][j] > 40:
      list_a[i][j] = 0

842 ms ± 302 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# проверим, что изменение выполнено верно
print(list_a[0][:10])

[0, 3, 0, 0, 21, 15, 17, 33, 0, 3]


In [ ]:
%%timeit
# выполним то же условие, но с массивом
np.where(a>40,0,a)

57.1 ms ± 9.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# проверим, что изменение выполнено верно
print(np.where(a>40,0,a)[0,:10])

[ 0  3  0  0 21 15 17 33  0  3]


Правильно используя массивы numpy, можно значительно сэкономить время выполнения кода, что зачастую является очень важным фактором при работе с большими данными.